version: '3'

services:
  front:
    image: frostyfinds-front
    ports:
      - "80:80"
    volumes:
      - ./front/dist/frostyfinds:/usr/share/nginx/html
    depends_on:
      - back

  back:
    image: frostyfinds-back
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_DATABASE=frostyfinds
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=frostyfinds
    volumes:
      - ./back/dbdata:/var/lib/mysql